name: ml_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - alembic=1.14.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.8.0=hb921021_15
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h831e299_5
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.7=hf454442_0
  - aws-c-sdkutils=0.2.1=h4e1184b_4
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.7=hd92328a_7
  - aws-sdk-cpp=1.11.458=hc430e4a_4
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - blas=1.0=openblas
  - bokeh=3.6.2=pyhd8ed1ab_1
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cffi=1.17.1=py312h06ac9bb_0
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.9.0=pyh707e725_1
  - contourpy=1.3.1=py312h68727a3_0
  - cytoolz=1.0.1=py312h66e93f0_0
  - dal=2025.0.0=hf2ce2f3_959
  - dask=2024.12.1=pyhd8ed1ab_0
  - dask-core=2024.12.1=pyhd8ed1ab_0
  - dask-expr=1.1.21=pyhd8ed1ab_0
  - dask-jobqueue=0.9.0=pyhd8ed1ab_0
  - distributed=2024.12.1=pyhd8ed1ab_0
  - dpcpp-cpp-rt=2025.0.4=ha770c72_1519
  - expat=2.6.4=h6a678d5_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - greenlet=3.1.1=py312h2ec8cdc_1
  - h2=4.1.0=pyhd8ed1ab_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - intel-cmplr-lib-rt=2025.0.4=h04fd95a_1519
  - intel-cmplr-lib-ur=2025.0.4=h04fd95a_1519
  - intel-cmplr-lic-rt=2025.0.4=ha770c72_1519
  - intel-opencl-rt=2025.0.4=h5a16d59_1519
  - intel-sycl-rt=2025.0.4=h7a4b287_1519
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=py312h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_2
  - libarrow=18.1.0=hd595efa_7_cpu
  - libarrow-acero=18.1.0=hcb10f89_7_cpu
  - libarrow-dataset=18.1.0=hcb10f89_7_cpu
  - libarrow-substrait=18.1.0=h08228c5_7_cpu
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.71=h39aace5_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libfabric=1.22.0=ha770c72_3
  - libfabric1=1.22.0=ha594dbc_3
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.33.0=h2b5623c_1
  - libgoogle-cloud-storage=2.33.0=h0121fbd_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.67.1=h25350d4_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libparquet=18.1.0=h081d1f1_7_cpu
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=257.2=h3dc2cb9_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hd9ff511_3
  - libudev1=257.2=h9a4d06a_0
  - libutf8proc=2.9.0=hb9d3cd8_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.1.3=cpu_h3a1dfae_0
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py312h374181b_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py312hf0f0c11_2
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.8=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h178313f_1
  - mpi=1.0=mpich
  - mpich=4.2.3=h239ebd3_102
  - msgpack-python=1.1.0=py312h68727a3_0
  - ncurses=6.5=he02047a_1
  - numba=0.60.0=py312h83e6fd3_0
  - numexpr=2.10.1=py312hd28fd6d_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.0=h7b32b05_1
  - optuna=4.1.0=pyhd8ed1ab_1
  - orc=2.0.3=h12ee42a_2
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312h6a678d5_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pip=24.2=py312h06a4308_0
  - psutil=6.1.1=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py-xgboost=2.1.3=cpu_pyhd3de297_0
  - py-xgboost-cpu=2.1.3=pyhac85b48_0
  - pyarrow=18.1.0=py312h7900ff3_0
  - pyarrow-core=18.1.0=py312h01725c0_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.8=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - rdma-core=55.0=h5888daf_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h5eee18b_0
  - s2n=1.5.10=hb5b8611_0
  - scikit-learn=1.5.2=py312h6a678d5_0
  - scikit-learn-intelex=2025.0.0=py312h965d50b_1
  - scipy=1.14.1=py312h2809609_0
  - setuptools=75.1.0=py312h06a4308_0
  - shap=0.46.0=cpu_py312h7f70532_1
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.36=py312h66e93f0_0
  - sqlite=3.47.2=h9eae976_0
  - tbb=2022.0.0=hceb3a55_0
  - tblib=3.0.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=h04d1e81_0
  - ucx=1.17.0=h53fb5aa_4
  - umf=2025.0.4=hb3528f5_6
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wheel=0.44.0=py312h06a4308_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2024.9.0=pyhd8ed1ab_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - category-encoders==2.6.4
      - cycler==0.12.1
      - fonttools==4.55.3
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - mrmr-selection==0.2.8
      - optuna-integration==4.1.0
      - patsy==1.0.1
      - pillow==11.1.0
      - plotly==5.24.1
      - polars==1.18.0
      - pyparsing==3.2.1
      - skrebate==0.62
      - statsmodels==0.14.4
      - tenacity==9.0.0
      - zoofs==0.1.26
